---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: justin-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # Copy system files and home directory templates
  - type: files
    files:
      - source: home
        destination: /var/home # User home directory templates
      - source: system
        destination: / # System files and configurations

  # Install RPM Fusion repositories
  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm

  # DNF packages
  - type: dnf
    install:
      packages:
        - micro
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # Default flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
      - scope: user

  # Ensure the Microsoft GPG key is present before repo configuration
  - type: script
    scripts:
      - ensure-microsoft-gpg.sh

  # Import consolidated modules
  - from-file: packages.yml
  - from-file: system-services.yml
  - from-file: common-flatpaks.yml

  # Microsoft Core Fonts dependencies and installer
  - type: rpm-ostree
    install:
      - curl
      - cabextract
      - xorg-x11-font-utils # Required by msttcore-fonts-installer
      - fontconfig

  # Configure shells and install Microsoft fonts (BEFORE changing /bin/sh)
  - type: script
    scripts:
      - install-ms-fonts-build.sh
      - set-default-shell-zsh.sh

  - type: signing

  # Change /bin/sh to dash (MUST BE LAST - after all package operations)
  - type: script
    scripts:
      - set-dash-as-sh.sh
