---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: justin-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # Copy system files and home directory templates
  - type: files
    files:
      - source: system
        destination: / # System files and configurations

  # Install RPM Fusion repositories with resilient mirror selection
  - type: script
    scripts:
      - install-rpmfusion-release.sh

  # DNF packages
  - type: dnf
    install:
      packages:
        - micro
    remove:
      packages:
        - firefox
        - firefox-langpacks

  # Default flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
      - scope: user

  # Ensure the Microsoft GPG key is present before repo configuration
  - type: script
    scripts:
      - ensure-microsoft-gpg.sh

  # Import consolidated modules
  - from-file: packages.yml
  - from-file: system-services.yml
  - from-file: common-flatpaks.yml

  # Shared Microsoft font installation and shell configuration sequence
  - from-file: shared-fonts-shell.yml

  # Disable systemd-oomd to prevent conflicts with nohang
  - type: script
    scripts:
      - disable-systemd-oomd.sh

  - type: signing

  # Change /bin/sh to dash (MUST BE LAST - after all package operations)
  - type: script
    scripts:
      - set-dash-as-sh.sh
